# ========================================
# VaultBank API — Perfil Docker (MySQL)
# ========================================

# MySQL Connection
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:mysql}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:vaultbank}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=${MYSQL_USER:vaultbank}
spring.datasource.password=${MYSQL_PASSWORD:vault@2026}

# Desativar H2
spring.h2.console.enabled=false

# JPA para MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
